server:
  port: 8082

spring:
  application:
    name: leave-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/leave_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

jwt:
  secret: ${JWT_SECRET:bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXk=}

employee-service:
  url: ${EMPLOYEE_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
